### ISSUE TITLE
Layout: news / views

### ISSUE THREAD

**Issue by greatislander** [inclusive-design/wecount.inclusivedesign.ca#116]
## Is your feature request related to a problem? Please describe.

Build mobile and desktop styles for news/views pages.

## Describe the solution you'd like

See [Figma](https://www.figma.com/file/0lcLol3X5MmOXackT2YbHJ/WeCount-website?node-id=239%3A1). Vue methods should be used to filter posts by tag (`v-bind`, probably).

## Describe alternatives you've considered

Not applicable.

## Additional context

Not applicable.

**Comment by TeddTech** [comment]
While working on this issue I have some questions.

I gave the `NewsItem` component the same styling as the Figma wireframe but the result does not look correct. I was wondering what I am doing incorrectly.

```css
.news-item {
  background: #fff;
  box-sizing: border-box;
  height: rem(252);
  width: rem(397);
}
```
